
/*заполнение таблицы*/
INSERT INTO FIGURE
VALUES (1, 2, 4, 1)
INSERT INTO FIGURE
VALUES (1, 0, 0, 2)
INSERT INTO FIGURE
VALUES (1, 4, 2, 3)

INSERT INTO FIGURE
VALUES (2, 0, 0, 1)
INSERT INTO FIGURE
VALUES (2, 0, 4, 2)
INSERT INTO FIGURE
VALUES (2, 2, 2, 3)

